const Movies = [
    { id: 1,
      Titel: "Titanic",
      Discription:"Incorporating both historical and fictionalized aspects, it is based on accounts of the sinking of RMS Titanic in 1912. Kate Winslet and Leonardo DiCaprio star as members of different social classes who fall in love during the ship's maiden voyage.      ",
      rating: 4,
      Url: "https://goldenglobes.com/wp-content/uploads/2023/10/1998-titanic.jpg?w=640",
      trailer_ID:"CHekzSiZjrY",
    },
    {   id: 2,
        Titel: "Night School",
        Discription:"Night School is a 2018 American buddy comedy film directed by Malcolm D. Lee, produced with Will Packer and Kevin Hart, written by Hart, Harry Ratchford, Joey Wells, Matt Kellard, Nicholas Stoller and John Hamburg, and starring Hart, Tiffany Haddish, Rob Riggle, and Romany Malco",
        rating: 3,
        Url: "https://m.media-amazon.com/images/I/71E04LC+W6L._AC_UF1000,1000_QL80_.jpg",
        trailer_ID:"t9QtXGirWf0",
      },
      { id: 3,
        Titel: "Ride Along 2",
        Discription:"Ride Along 2 is a 2016 American buddy cop action comedy film directed by Tim Story and written by Phil Hay and Matt Manfredi. It is the sequel to the 2014 film Ride Along. The film stars Ice Cube, Kevin Hart, Ken Jeong, Benjamin Bratt, Olivia Munn, Bruce McGill and Tika Sumpter.",
        rating: 2,
        Url: "https://m.media-amazon.com/images/I/91LJil4MosL._AC_UF1000,1000_QL80_.jpg",
        trailer_ID:"Eh0w35EiG_I",
      },
      { id: 4,
        Titel: "The Nice Guys",
        Discription:"The Nice Guys is a 2016 American neo-noir buddy action comedy film directed and co-written (alongside Anthony Bagarozzi) by Shane Black, produced by Joel Silver, and starring Russell Crowe and Ryan Gosling in the title roles with Angourie Rice, Matt Bomer, Margaret Qualley, Keith David and Kim Basinger",
        rating: 5,
        Url: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p12356386_p_v8_ae.jpg",
        trailer_ID:"PHHvBScPGuA",
      },                

]

export default Movies;